name: Deploy Firebase Functions (prod)

on:
  push:
    branches: [ main ]
    # paths:
    #   - 'functions/**'
    #   - 'firebase.json'
    #   - '.github/workflows/functions-deploy.yml'
  workflow_dispatch:
  
concurrency:
  group: functions-deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Auth to Google Cloud (Service Account)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: online-check-in-23087

      - name: Enable required APIs (explicit)
        run: |
          gcloud services enable firebaseextensions.googleapis.com

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@13

      - name: Install deps (functions)
        working-directory: functions
        run: npm ci || npm install

      - name: Create .env for Functions
        working-directory: functions
        shell: bash
        run: |
          {
            echo "ADMIN_KEY=${{ secrets.ADMIN_KEY }}";
            echo "APP_ALLOWED_ORIGINS=${{ secrets.APP_ALLOWED_ORIGINS }}";
          } > .env

      - name: Build (functions)
        working-directory: functions
        run: |
          npm run build
          test -f lib/index.js && echo "Built: lib/index.js exists"

      # ★ 追加：firebase-functions バイナリに実行権限を付与（EACCES対策）
      - name: Fix exec permission for firebase-functions analyzer
        working-directory: functions
        run: |
          ls -l node_modules/.bin || true
          chmod +x node_modules/.bin/firebase-functions || true
          ls -l node_modules/.bin/firebase-functions || true

      # 解析前にモジュールが読めるか sanity check（CJS想定）
      - name: Sanity check compiled module
        working-directory: functions
        run: |
          node -e "const m=require('./lib/index.js'); console.log('exports:', Object.keys(m)); if(!('api' in m)){ console.error('Export \"api\" not found'); process.exit(2); }"

      - name: Deploy Functions (debug)
        run: firebase deploy --only functions --project online-check-in-23087 --non-interactive --debug
